const crypto=require('crypto');
class ListeningError extends Error{constructor(message,code='INVALID_LISTENING_WORKFLOW'){super(message);this.code=code;}}
const clean=(v,n,max=5000)=>{const s=String(v||'').trim();if(!s)throw new ListeningError(`${n} is required`);if(s.length>max)throw new ListeningError(`${n} is too long`);return s;};
function validateSurvey(input){const min=Number(input.minimum_cohort_size||5),retention=Number(input.retention_days);if(!Number.isInteger(min)||min<5)throw new ListeningError('minimum_cohort_size must be at least 5');if(!Number.isInteger(retention)||retention<1||retention>730)throw new ListeningError('retention_days must be between 1 and 730');return{name:clean(input.name,'name',200),purpose:clean(input.purpose,'purpose',1000),consent_notice:clean(input.consent_notice,'consent_notice',2000),minimum_cohort_size:min,retention_days:retention,questions:Array.isArray(input.questions)?input.questions.slice(0,100):[]};}
function pseudonymize(subject,tenant,key){if(!key||key.length<32||key.startsWith('replace-'))throw new ListeningError('ANALYTICS_PSEUDONYM_KEY must contain at least 32 non-placeholder characters');return crypto.createHmac('sha256',key).update(`${tenant}:${subject}`).digest('hex');}
function encryptText(value,keyHex){if(!/^[a-f0-9]{64}$/i.test(String(keyHex||'')))throw new ListeningError('RAW_TEXT_ENCRYPTION_KEY must be 32-byte hex');const iv=crypto.randomBytes(12),key=Buffer.from(keyHex,'hex'),cipher=crypto.createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return`${iv.toString('hex')}:${cipher.getAuthTag().toString('hex')}:${encrypted.toString('hex')}`;}
function decryptText(value,keyHex){const[ivHex,tagHex,dataHex]=String(value).split(':');const decipher=crypto.createDecipheriv('aes-256-gcm',Buffer.from(keyHex,'hex'),Buffer.from(ivHex,'hex'));decipher.setAuthTag(Buffer.from(tagHex,'hex'));return Buffer.concat([decipher.update(Buffer.from(dataHex,'hex')),decipher.final()]).toString('utf8');}
function aggregateCohort(responses,minimum=5){if(responses.length<minimum)throw new ListeningError(`cohort suppressed: ${minimum} responses required`,'COHORT_SUPPRESSED');const lex={positive:['good','supported','fair','happy','improved'],negative:['bad','unsafe','unfair','stress','retaliation']};let pos=0,neg=0;for(const value of responses){const t=String(value).toLowerCase();pos+=lex.positive.filter(w=>t.includes(w)).length;neg+=lex.negative.filter(w=>t.includes(w)).length;}const total=Math.max(1,pos+neg);return{response_count:responses.length,sentiment_score:(pos-neg)/total,positive_signals:pos,negative_signals:neg,uncertainty:Math.min(.5,1/Math.sqrt(responses.length)),method:'deterministic_lexicon_v1'};}
function assertActionTransition(from,to){const a={proposed:['reviewed','rejected'],reviewed:['approved','rejected'],approved:['in_progress'],in_progress:['completed'],rejected:[],completed:[]};if(!(a[from]||[]).includes(to))throw new ListeningError(`action transition ${from} -> ${to} is not allowed`);}
module.exports={ListeningError,validateSurvey,pseudonymize,encryptText,decryptText,aggregateCohort,assertActionTransition};
