export const features = [
  {
    key: 'surveys',
    title: 'Employee Surveys',
    description: 'Analyze employee survey responses with AI-powered sentiment detection',
    icon: '📋',
    color: '#6366f1',
    apiPath: '/surveys',
    columns: ['employee_name', 'department', 'question', 'sentiment_label', 'sentiment_score'],
    columnLabels: { employee_name: 'Employee', department: 'Department', question: 'Question', sentiment_label: 'Sentiment', sentiment_score: 'Score' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'survey_date', label: 'Survey Date', type: 'date' },
      { name: 'question', label: 'Question', type: 'text', required: true },
      { name: 'response', label: 'Response', type: 'textarea', required: true },
      { name: 'sentiment_score', label: 'Sentiment Score (0-1)', type: 'number', step: '0.01', min: '0', max: '1' },
      { name: 'sentiment_label', label: 'Sentiment', type: 'select', options: ['Positive', 'Neutral', 'Negative'] },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'department-analytics',
    title: 'Department Analytics',
    description: 'Track and compare sentiment metrics across departments',
    icon: '📊',
    color: '#8b5cf6',
    apiPath: '/department-analytics',
    columns: ['department', 'period', 'avg_sentiment', 'positive_pct', 'negative_pct'],
    columnLabels: { department: 'Department', period: 'Period', avg_sentiment: 'Avg Sentiment', positive_pct: 'Positive %', negative_pct: 'Negative %' },
    fields: [
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'period', label: 'Period', type: 'text', required: true },
      { name: 'avg_sentiment', label: 'Avg Sentiment (0-1)', type: 'number', step: '0.01', min: '0', max: '1' },
      { name: 'total_responses', label: 'Total Responses', type: 'number' },
      { name: 'positive_pct', label: 'Positive %', type: 'number', step: '0.01' },
      { name: 'neutral_pct', label: 'Neutral %', type: 'number', step: '0.01' },
      { name: 'negative_pct', label: 'Negative %', type: 'number', step: '0.01' },
      { name: 'key_themes', label: 'Key Themes', type: 'textarea' },
    ],
    aiField: 'ai_insights',
  },
  {
    key: 'pulse-checks',
    title: 'Pulse Checks',
    description: 'Quick employee mood and wellness check-ins with AI insights',
    icon: '💓',
    color: '#ec4899',
    apiPath: '/pulse-checks',
    columns: ['employee_name', 'department', 'mood', 'energy_level', 'stress_level'],
    columnLabels: { employee_name: 'Employee', department: 'Department', mood: 'Mood', energy_level: 'Energy', stress_level: 'Stress' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'mood', label: 'Mood', type: 'select', options: ['Happy', 'Content', 'Energetic', 'Motivated', 'Focused', 'Inspired', 'Calm', 'Determined', 'Neutral', 'Tired', 'Stressed', 'Anxious', 'Frustrated', 'Overwhelmed'] },
      { name: 'energy_level', label: 'Energy Level (1-10)', type: 'number', min: '1', max: '10' },
      { name: 'stress_level', label: 'Stress Level (1-10)', type: 'number', min: '1', max: '10' },
      { name: 'comment', label: 'Comment', type: 'textarea' },
      { name: 'check_date', label: 'Check Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'feedback-analysis',
    title: 'Feedback Analysis',
    description: 'AI-powered analysis of employee feedback with topic extraction',
    icon: '💬',
    color: '#06b6d4',
    apiPath: '/feedback-analysis',
    columns: ['employee_name', 'department', 'feedback_type', 'sentiment_score', 'key_topics'],
    columnLabels: { employee_name: 'Employee', department: 'Department', feedback_type: 'Type', sentiment_score: 'Sentiment', key_topics: 'Topics' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'feedback_type', label: 'Feedback Type', type: 'select', options: ['Peer Review', 'Self Assessment', '360 Feedback', 'Manager Review'] },
      { name: 'feedback_text', label: 'Feedback Text', type: 'textarea', required: true },
      { name: 'sentiment_score', label: 'Sentiment Score (0-1)', type: 'number', step: '0.01', min: '0', max: '1' },
      { name: 'key_topics', label: 'Key Topics', type: 'text' },
      { name: 'submitted_date', label: 'Submitted Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'retention-risks',
    title: 'Retention Risks',
    description: 'AI-predicted flight risk scoring with intervention recommendations',
    icon: '⚠️',
    color: '#f59e0b',
    apiPath: '/retention-risks',
    columns: ['employee_name', 'department', 'tenure_years', 'risk_score', 'risk_factors'],
    columnLabels: { employee_name: 'Employee', department: 'Department', tenure_years: 'Tenure', risk_score: 'Risk Score', risk_factors: 'Risk Factors' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'tenure_years', label: 'Tenure (Years)', type: 'number', step: '0.1' },
      { name: 'risk_score', label: 'Risk Score (0-1)', type: 'number', step: '0.01', min: '0', max: '1' },
      { name: 'risk_factors', label: 'Risk Factors', type: 'textarea' },
      { name: 'recommended_actions', label: 'Recommended Actions', type: 'textarea' },
      { name: 'last_assessed', label: 'Last Assessed', type: 'date' },
    ],
    aiField: 'ai_prediction',
  },
  {
    key: 'engagement-scores',
    title: 'Engagement Scores',
    description: 'Track employee engagement levels with trend analysis',
    icon: '🎯',
    color: '#22c55e',
    apiPath: '/engagement-scores',
    columns: ['employee_name', 'department', 'score', 'category', 'trend'],
    columnLabels: { employee_name: 'Employee', department: 'Department', score: 'Score', category: 'Category', trend: 'Trend' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'score', label: 'Score (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'category', label: 'Category', type: 'select', options: ['Highly Engaged', 'Engaged', 'Partially Engaged', 'Disengaged'] },
      { name: 'factors', label: 'Factors', type: 'textarea' },
      { name: 'trend', label: 'Trend', type: 'select', options: ['Improving', 'Stable', 'Declining'] },
      { name: 'assessed_date', label: 'Assessed Date', type: 'date' },
    ],
    aiField: 'ai_recommendations',
  },
  {
    key: 'team-morale',
    title: 'Team Morale',
    description: 'Monitor team-level morale with participation tracking',
    icon: '👥',
    color: '#3b82f6',
    apiPath: '/team-morale',
    columns: ['team_name', 'department', 'morale_score', 'participation_rate', 'highlights'],
    columnLabels: { team_name: 'Team', department: 'Department', morale_score: 'Morale', participation_rate: 'Participation %', highlights: 'Highlights' },
    fields: [
      { name: 'team_name', label: 'Team Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'morale_score', label: 'Morale Score (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'participation_rate', label: 'Participation Rate %', type: 'number', step: '0.01' },
      { name: 'highlights', label: 'Highlights', type: 'textarea' },
      { name: 'concerns', label: 'Concerns', type: 'textarea' },
      { name: 'survey_date', label: 'Survey Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'exit-interviews',
    title: 'Exit Interviews',
    description: 'Analyze departure patterns and identify preventable attrition',
    icon: '🚪',
    color: '#ef4444',
    apiPath: '/exit-interviews',
    columns: ['employee_name', 'department', 'exit_date', 'exit_reason', 'preventable'],
    columnLabels: { employee_name: 'Employee', department: 'Department', exit_date: 'Exit Date', exit_reason: 'Reason', preventable: 'Preventable' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'exit_date', label: 'Exit Date', type: 'date', required: true },
      { name: 'tenure_years', label: 'Tenure (Years)', type: 'number', step: '0.1' },
      { name: 'exit_reason', label: 'Exit Reason', type: 'text', required: true },
      { name: 'feedback', label: 'Feedback', type: 'textarea' },
      { name: 'preventable', label: 'Preventable', type: 'select', options: ['true', 'false'] },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'anonymous-reports',
    title: 'Anonymous Reports',
    description: 'Safely collect and analyze anonymous employee feedback',
    icon: '🔒',
    color: '#a855f7',
    apiPath: '/anonymous-reports',
    columns: ['department', 'category', 'severity', 'status', 'submitted_date'],
    columnLabels: { department: 'Department', category: 'Category', severity: 'Severity', status: 'Status', submitted_date: 'Date' },
    fields: [
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['Work Environment', 'Management', 'Compensation', 'Staffing', 'Work-Life Balance', 'Process', 'Communication', 'Tools', 'Safety', 'Diversity', 'Resources', 'Ethics', 'Training', 'Transparency'] },
      { name: 'report_text', label: 'Report', type: 'textarea', required: true },
      { name: 'severity', label: 'Severity', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'Under Review', 'Resolved'] },
      { name: 'submitted_date', label: 'Submitted Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'performance-reviews',
    title: 'Performance Reviews',
    description: 'Track performance review sentiment and development areas',
    icon: '⭐',
    color: '#f97316',
    apiPath: '/performance-reviews',
    columns: ['employee_name', 'department', 'reviewer', 'rating', 'sentiment_score'],
    columnLabels: { employee_name: 'Employee', department: 'Department', reviewer: 'Reviewer', rating: 'Rating', sentiment_score: 'Sentiment' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'reviewer', label: 'Reviewer', type: 'text' },
      { name: 'rating', label: 'Rating (0-5)', type: 'number', step: '0.1', min: '0', max: '5' },
      { name: 'strengths', label: 'Strengths', type: 'textarea' },
      { name: 'improvements', label: 'Areas for Improvement', type: 'textarea' },
      { name: 'sentiment_score', label: 'Sentiment Score (0-1)', type: 'number', step: '0.01', min: '0', max: '1' },
      { name: 'review_date', label: 'Review Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'onboarding-feedback',
    title: 'Onboarding Feedback',
    description: 'Track new hire experience and optimize the onboarding process',
    icon: '🎓',
    color: '#14b8a6',
    apiPath: '/onboarding-feedback',
    columns: ['employee_name', 'department', 'week_number', 'satisfaction_score', 'challenges'],
    columnLabels: { employee_name: 'Employee', department: 'Department', week_number: 'Week', satisfaction_score: 'Satisfaction', challenges: 'Challenges' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'week_number', label: 'Week Number', type: 'number', min: '1', required: true },
      { name: 'satisfaction_score', label: 'Satisfaction (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'challenges', label: 'Challenges', type: 'textarea' },
      { name: 'suggestions', label: 'Suggestions', type: 'textarea' },
      { name: 'submitted_date', label: 'Submitted Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'benefits-satisfaction',
    title: 'Benefits Satisfaction',
    description: 'Measure employee satisfaction with benefits packages',
    icon: '🎁',
    color: '#10b981',
    apiPath: '/benefits-satisfaction',
    columns: ['employee_name', 'department', 'benefit_type', 'satisfaction_score', 'comments'],
    columnLabels: { employee_name: 'Employee', department: 'Department', benefit_type: 'Benefit', satisfaction_score: 'Score', comments: 'Comments' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'benefit_type', label: 'Benefit Type', type: 'select', options: ['Health Insurance', 'Retirement Plan', 'PTO Policy', 'Wellness Program', 'Remote Work', 'Professional Development'] },
      { name: 'satisfaction_score', label: 'Satisfaction (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'comments', label: 'Comments', type: 'textarea' },
      { name: 'survey_date', label: 'Survey Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'work-life-balance',
    title: 'Work-Life Balance',
    description: 'Monitor work-life balance metrics and overtime patterns',
    icon: '⚖️',
    color: '#0ea5e9',
    apiPath: '/work-life-balance',
    columns: ['employee_name', 'department', 'balance_score', 'overtime_hours', 'flexibility_rating'],
    columnLabels: { employee_name: 'Employee', department: 'Department', balance_score: 'Balance', overtime_hours: 'Overtime Hrs', flexibility_rating: 'Flexibility' },
    fields: [
      { name: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'balance_score', label: 'Balance Score (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'overtime_hours', label: 'Overtime Hours', type: 'number', step: '0.1' },
      { name: 'flexibility_rating', label: 'Flexibility (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'comments', label: 'Comments', type: 'textarea' },
      { name: 'assessed_date', label: 'Assessed Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'leadership-ratings',
    title: 'Leadership Ratings',
    description: 'Evaluate leadership effectiveness across dimensions',
    icon: '👑',
    color: '#d946ef',
    apiPath: '/leadership-ratings',
    columns: ['leader_name', 'department', 'rated_by', 'overall_score', 'communication_score'],
    columnLabels: { leader_name: 'Leader', department: 'Department', rated_by: 'Rated By', overall_score: 'Overall', communication_score: 'Communication' },
    fields: [
      { name: 'leader_name', label: 'Leader Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'rated_by', label: 'Rated By', type: 'text' },
      { name: 'communication_score', label: 'Communication (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'vision_score', label: 'Vision (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'support_score', label: 'Support (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'overall_score', label: 'Overall (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'comments', label: 'Comments', type: 'textarea' },
      { name: 'rating_date', label: 'Rating Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
  {
    key: 'culture-index',
    title: 'Culture Index',
    description: 'Measure organizational culture dimensions against benchmarks',
    icon: '🏛️',
    color: '#64748b',
    apiPath: '/culture-index',
    columns: ['department', 'dimension', 'score', 'benchmark', 'gap'],
    columnLabels: { department: 'Department', dimension: 'Dimension', score: 'Score', benchmark: 'Benchmark', gap: 'Gap' },
    fields: [
      { name: 'department', label: 'Department', type: 'select', required: true },
      { name: 'dimension', label: 'Dimension', type: 'text', required: true },
      { name: 'score', label: 'Score (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'benchmark', label: 'Benchmark (0-10)', type: 'number', step: '0.1', min: '0', max: '10' },
      { name: 'gap', label: 'Gap', type: 'number', step: '0.1' },
      { name: 'comments', label: 'Comments', type: 'textarea' },
      { name: 'survey_date', label: 'Survey Date', type: 'date' },
    ],
    aiField: 'ai_analysis',
  },
];

export const departments = [
  'Engineering', 'Marketing', 'Sales', 'HR', 'Finance',
  'Operations', 'Product', 'Design', 'Legal', 'Support'
];
